ntkgp option in predict.gp_inference
google/neural-tangents pull request #93
Opened 2020-12-30 20:01 UTC by bobby-he

added `get='ntkgp'` option in nt.predict.gp_inference and also added test in tests.predict_test.testGpInference

2020-12-30 21:05 UTC, bobby-he commented
@googlebot I signed it!
________________________________
From: google-cla[bot] <notifications@github.com>
Sent: Wednesday, December 30, 2020 8:01 PM
To: google/neural-tangents <neural-tangents@noreply.github.com>
Cc: Bobby He <bobby.he@spc.ox.ac.uk>; Author <author@noreply.github.com>
Subject: Re: [google/neural-tangents] ntkgp option in predict.gp_inference (#93)


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/ to sign.

Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

________________________________
What to do if you already signed the CLA
Individual signers

  *   It's possible we don't have your GitHub username or you're using a different email address on your commit. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.

Corporate signers

  *   Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to go/cla#troubleshoot<http://go/cla#troubleshoot> (Public version<https://opensource.google/docs/cla/#troubleshoot>).
  *   The email used to register you as an authorized contributor must be the email used for the Git commit. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   The email used to register you as an authorized contributor must also be attached to your GitHub account<https://github.com/settings/emails>.

ℹ️ Googlers: Go here<https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fneural-tangents%2Fpull%2F93> for more info.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/google/neural-tangents/pull/93#issuecomment-752740690>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKPOOKWATDIHZXB6SMSIFZLSXOBJ3ANCNFSM4VOVJM2A>.

2021-01-06 23:07 UTC, romanngg requested changes
Thanks a lot for the change, it looks great! Left some minor comments, the main one regarding whether it could support `get=('ntk', 'nngp', 'ntkgp')`, lmk what you think!

2021-01-09 22:41 UTC, bobby-he commented on neural_tangents/predict.py
> +                 k_test_test: np.ndarray = None
Yeah good idea! I just added some changes that allow `k_test_test` to be an array/namedtuple/kernel and a few more that test when get is a tuple containing `ntkgp`. Lmk what you think!

2021-01-22 05:58 UTC, merged

2021-01-22 05:59 UTC, romanngg commented on neural_tangents/predict.py
> +                 k_test_test: np.ndarray = None
Great job, thank you for the contribution!